services:
  redis:
    image: redis:latest
    container_name: redis_websocket_chat
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
      - ./redis.conf:/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}